# Generated by Django 5.0.6 on 2025-08-17 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0003_preinscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='recorrido',
            name='recorrido_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PuntoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('orden', models.PositiveIntegerField()),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='recorridos.ruta')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
