# Generated by Django 5.0.6 on 2025-08-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0005_inscripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recorrido',
            options={'ordering': ['fecha', 'hora_inicio'], 'verbose_name': 'Recorrido', 'verbose_name_plural': 'Recorridos'},
        ),
        migrations.RemoveField(
            model_name='recorrido',
            name='created',
        ),
        migrations.RemoveField(
            model_name='recorrido',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='recorrido',
            name='updated',
        ),
        migrations.AddField(
            model_name='recorrido',
            name='hora_inicio',
            field=models.TimeField(default='08:00', verbose_name='Hora de inicio'),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='nombre',
            field=models.CharField(default='Recorrido sin nombre', max_length=200, verbose_name='Nombre del recorrido'),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='punto_final',
            field=models.CharField(default='Punto final por defecto', max_length=200, verbose_name='Punto final'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recorrido',
            name='tipo',
            field=models.CharField(choices=[('proximo', 'Próximo'), ('realizado', 'Realizado')], default='proximo', max_length=10, verbose_name='Tipo de recorrido'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='ciudad',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='estado',
            field=models.CharField(max_length=100, verbose_name='Estado / Región'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='fecha',
            field=models.DateField(verbose_name='Fecha del recorrido'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='recorridos/', verbose_name='Fotografía / Imagen'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='kilometros',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Kilómetros'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='punto_inicio',
            field=models.CharField(max_length=200, verbose_name='Punto de inicio'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='recorrido_realizado',
            field=models.BooleanField(default=False, verbose_name='¿Recorrido realizado?'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='tiempo_estimado',
            field=models.CharField(max_length=100, verbose_name='Tiempo estimado'),
        ),
    ]
