# Generated by Django 5.0.6 on 2025-08-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0006_alter_recorrido_options_remove_recorrido_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inscripcion',
        ),
    ]
