# Generated by Django 5.0.6 on 2025-08-19 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0008_inscripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recorridos',
            new_name='EstadoRecorrido',
        ),
        migrations.RenameModel(
            old_name='Mapas',
            new_name='Mapa',
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'ordering': ['-fecha_inscripcion'], 'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='puntoruta',
            options={'ordering': ['orden'], 'verbose_name': 'Punto de Ruta', 'verbose_name_plural': 'Puntos de Ruta'},
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripción'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='recorrido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='recorridos.recorrido', verbose_name='Recorrido'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='recorrido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preinscripciones', to='recorridos.recorrido', verbose_name='Recorrido'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Ruta'),
        ),
    ]
