# Generated by Django 5.0.6 on 2025-08-19 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0009_rename_recorridos_estadorecorrido_rename_mapas_mapa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntosMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='recorridos.recorrido')),
            ],
        ),
        migrations.DeleteModel(
            name='Mapa',
        ),
        migrations.DeleteModel(
            name='PuntoRuta',
        ),
    ]
